<a href="https://colab.research.google.com/github/PavanChintha/Machine-Learning/blob/main/fods.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Assignment 1 (FODS)

Name : Chintha Pavan

Roll No : CB.EN.U4CSE20312


In [3]:
#Q1 
s = {"aman", "222", 777, 400.4}
t = tuple(s)
print(t)

(400.4, 777, 'aman', '222')


In [4]:
#Q2 
dicti = {'Roll.no':'CB.EN.U4CSE20312', 'Lastname':'Pavan', 'Firstname':'Chintha', 'D.O.B':'05-10-2002'}
print(dicti.keys())
print(dicti.values())

dict_keys(['Roll.no', 'Lastname', 'Firstname', 'D.O.B'])
dict_values(['CB.EN.U4CSE20312', 'Pavan', 'Chintha', '05-10-2002'])


In [6]:
#Q3 
import numpy as np
np.random.seed(20)
rdarr = np.random.randint(0,20,size=(2,2))
print(rdarr)


[[ 3 15]
 [ 9 11]]


In [8]:
#Q4
import random
print(random.uniform(0.0,0.1))
print('abs val of (-1234) =', abs(-1234))

0.07114681190140716
abs val of (-1234) = 1234


In [11]:
#Q5 
np.random.seed(20)
print('N = ',np.random.randint(20,90))

N =  35


In [13]:
#Q6 
popset = {11,12,13,14,15}
li = list(popset)
print(li[:3])
random.shuffle(li)
print(li)
print('Random num = ',random.choice(li))

[11, 12, 13]
[11, 15, 13, 12, 14]
Random num =  12


In [16]:
#Q7 
filei = open('/content/q7.txt','r')
print(filei.read())

The King is Dead, Long Live The King


In [23]:
#Q8 
print('Enter n: ')
n = int(input())

def aque(n):
  if(n>0):
    print('n is positive')
  elif(n==0):
    print('n is zero')
  else:
    print('n is negative')
aque(n)
arr = np.array([2,3,5,7,9])
def evensearch(arr):
  for i in arr:
    if(i %2 == 0):
      print("even number found", i)
      break
    else:
      continue
evensearch(arr)



Enter n: 
6
n is positive
even number found 2


In [22]:
#Q9 
string = "The King is Dead, Long Live The King"
print(string)
print(string[0])
print(string[3:5])
print(string[3:])
print(string.split())

The King is Dead, Long Live The King
T
 K
 King is Dead, Long Live The King
['The', 'King', 'is', 'Dead,', 'Long', 'Live', 'The', 'King']


In [24]:
#Q10 
ls = [1.0,4,5,8]
arr = np.array(ls)
print(arr)
print(arr[0:2])

[1. 4. 5. 8.]
[1. 4.]


In [25]:
#Q11 
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [26]:
#Q12 
arr = np.array([[1,2,3],[4,5,6]],dtype=float)
print(arr)
print('2nd row of 2D arr')
print(arr[1::])
print(arr[0:2,1])
print('Length =',len(arr))

[[1. 2. 3.]
 [4. 5. 6.]]
2nd row of 2D arr
[[4. 5. 6.]]
[2. 5.]
Length = 2


In [28]:
#Q13 
ls = [1,2,3,4,5,6,7,8,9,10]
arr = np.array(ls)
narr = arr.reshape(5,2)
print(narr)
print('Transpose =',narr.transpose())

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
Transpose = [[ 1  3  5  7  9]
 [ 2  4  6  8 10]]


In [29]:
#Q14 
import numpy as np
ls = [1,2,3]
arr = np.array(ls)
print('Array  =',arr)

Array  = [1 2 3]


In [31]:
#Q15 
arr = np.array([1,2,3])
print(arr)
arr.fill(9)
print(arr)

[1 2 3]
[9 9 9]


In [32]:
#Q16 
arr = np.array([2,4,5])
print('sum =',arr.sum())

sum = 11


In [33]:
#Q17 
arr = np.array([77,74,75])
print('product =',arr.prod())

product = 427350


In [34]:
#Q18 
import pandas as pd
arr = np.array([2,1,9,1,2,22,1,1,4,55,6,2,56])
df = pd.DataFrame(arr)
print('Mean =',df.mean())
print('Median =',df.median())
print('Variance =',df.var())
print('max =',df.max())
print('min =',df.min())
print('argmin =',np.argmin(arr))
print('argmax =',np.argmax(arr))
print('standarad deviation =',np.std(arr))

Mean = 0    12.461538
dtype: float64
Median = 0    2.0
dtype: float64
Variance = 0    397.935897
dtype: float64
max = 0    56
dtype: int64
min = 0    1
dtype: int64
argmin = 1
argmax = 12
standarad deviation = 19.165736192147232


In [36]:
#Q19 
arr = np.array([1,1,4,5,5,5,7])
np.sort(np.unique(arr))

array([1, 4, 5, 7])

In [39]:
#Q20 
arr1 = np.array([1,2,3])
arr2 = np.array([0,1,1])
print('dot product  =',np.dot(arr1,arr2))

dot product  = 5


In [38]:
#Q21
arr = np.array([[2,-12],[1,-5]])
egvalue,egvector = np.linalg.eig(arr)
print('Eigenvalues =',egvalue)
print('Eigenvector =', egvector)

Eigenvalues = [-1. -2.]
Eigenvector = [[0.9701425  0.9486833 ]
 [0.24253563 0.31622777]]
